name: BetterQuizsForEvents
version: '1.0-SNAPSHOT'
main: com.person98.betterquizsforevents.BetterQuizzesForEvents
api-version: 1.19
commands:
  addquestion:
    description: Add a question with four choices, question number, and choice colors
    usage: /addquestion "<question>" "<choice1>" "<choice2>" "<choice3>" "<choice4>" <question-number> <choice1color> <choice2color> <choice3color> <choice4color> <correct-answer>
  question:
    description: Display a question with specified question number to all players
    usage: /question <question-number>
  deathban:
    description: Toggles Death Bans
    usage: /deathban
  setdeathbanmessage:
    description: death ban message
    usage: /setdeathbanmessage <message>
  togglespectatorondeath:
    description: Toggle between survival and spectator mode on death.
    usage: /togglespectatorondeath
  exempt:
    description: Exempts a player from quiz questions and consequences.
    usage: /<command> <player>
  bqfehelp:
    description: Shows help and usage information for BetterQuizzesForEvents
    usage: /<command>
  explainquiz:
    description: Explain the quiz rules to all players.
    usage: /explainquiz
  permissions:
    betterquizsforevents.addquestion:
      description: Allows adding questions to the quiz
      default: op
    betterquizsforevents.question:
      description: Allows running a quiz question
      default: op
    betterquizsforevents.deathban:
      description: Allows toggling death bans
      default: op
    betterquizsforevents.setdeathbanmessage:
      description: Allows setting the death ban message
      default: op
    betterquizsforevents.togglespectatorondeath:
      description: Allows toggling between survival and spectator mode on death
      default: op
    betterquizsforevents.exempt:
      description: Allows exempting a player from quizzes
      default: op
    betterquizsforevents.bqfehelp:
      description: Allows access to the help command
      default: op
    betterquizsforevents.explainquiz:
      description: Allows access to the explain command
      default: op